"use client";

import { useState } from "react";
import { Zap, Copy, Check, Loader2, Download, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

// Placeholder outputs — in production these come from the Brand Intelligence Engine
const PLACEHOLDER_OUTPUTS = {
  midjourney: `photorealistic brand lifestyle photography, warm editorial tones, golden ratio composition, genuine human moments, clean negative space, soft natural lighting, documentary aesthetic, muted warm palette with [PRIMARY_HEX] and [SECONDARY_HEX] accents, high-end commercial quality, Leica-style rendering --ar 16:9 --style raw --v 6.1 --stylize 250`,

  dalle: `Create an image in the visual style of [BRAND_NAME]: warm, documentary-style photography with a genuine, unposed aesthetic. The colour palette draws from [PRIMARY], [SECONDARY], and [NEUTRAL] tones. Lighting should be soft and natural, avoiding harsh shadows or artificial studio flash. Composition uses strong negative space with subjects positioned off-centre. The overall mood is [MOOD]. Style: [PHOTOGRAPHY_STYLE]. Avoid: overly staged scenes, stock photography clichés, heavy post-processing, artificial colours.`,

  firefly: `Brand aesthetic: [BRAND_NAME]. Visual style: [PHOTOGRAPHY_STYLE], [ILLUSTRATION_STYLE]. Colour mood: warm, [COLOUR_TREATMENT]. Lighting: [LIGHTING]. Composition: [COMPOSITION_PRINCIPLES]. Mood: [MOOD]. Typography feel: [TYPEFACE_PRIMARY] — [TYPEFACE_CHARACTER]. Subject matter: [SUBJECTS].`,

  claude: `You are a brand content specialist for [BRAND_NAME]. You always write in the brand's voice and ensure all content meets brand standards.

## Brand Identity
[BRAND_NAME] is [BRAND_DESCRIPTION].

## Brand Personality
- [TRAIT_1]: [TRAIT_1_DESCRIPTION]
- [TRAIT_2]: [TRAIT_2_DESCRIPTION]
- [TRAIT_3]: [TRAIT_3_DESCRIPTION]

## Voice & Tone
[VOICE_PRINCIPLES]

Tone varies by context:
- Formal: [FORMAL_TONE]
- Informal: [INFORMAL_TONE]
- Celebratory: [CELEBRATORY_TONE]
- Serious: [SERIOUS_TONE]

## Vocabulary
Use: [USE_WORDS]
Avoid: [AVOID_WORDS]

## Grammar Rules
[GRAMMAR_NOTES]

## Visual Brand Context
When referencing or describing imagery for this brand:
- Photography: [PHOTOGRAPHY_STYLE] — [PHOTOGRAPHY_MOOD]
- Colour palette: [PRIMARY_COLOURS] with [SECONDARY_COLOURS] accents
- Typography: [TYPEFACE_PRIMARY] for display, [TYPEFACE_BODY] for body text

## Do
[DO_LIST]

## Don't
[DONT_LIST]`,

  designTokens: {
    css: `/* [BRAND_NAME] Design Tokens */
/* Generated by Brand Intelligence */

:root {
  /* Colour Palette */
  --color-primary: #1A1A2E;
  --color-primary-rgb: 26, 26, 46;
  --color-secondary: #E94560;
  --color-secondary-rgb: 233, 69, 96;
  --color-accent: #F5A623;
  --color-accent-rgb: 245, 166, 35;
  --color-neutral-100: #F8F8F8;
  --color-neutral-500: #6B6B6B;
  --color-neutral-900: #1A1A1A;

  /* Typography */
  --font-display: "GT Walsheim", "Helvetica Neue", Arial, sans-serif;
  --font-body: "GT Walsheim Light", "Helvetica Neue", Arial, sans-serif;

  /* Motion */
  --ease-enter: cubic-bezier(0.22, 1, 0.36, 1);
  --ease-exit: cubic-bezier(0.55, 0, 1, 0.45);
  --ease-standard: cubic-bezier(0.4, 0, 0.2, 1);
  --duration-fast: 150ms;
  --duration-standard: 300ms;
  --duration-slow: 500ms;
  --duration-deliberate: 800ms;
}`,
    json: `{
  "color": {
    "primary": { "value": "#1A1A2E", "type": "color" },
    "secondary": { "value": "#E94560", "type": "color" },
    "accent": { "value": "#F5A623", "type": "color" }
  },
  "font": {
    "display": { "family": { "value": "GT Walsheim", "type": "fontFamily" } },
    "body": { "family": { "value": "GT Walsheim Light", "type": "fontFamily" } }
  },
  "motion": {
    "easing": {
      "enter": { "value": "cubic-bezier(0.22, 1, 0.36, 1)", "type": "easing" },
      "exit": { "value": "cubic-bezier(0.55, 0, 1, 0.45)", "type": "easing" }
    },
    "duration": {
      "fast": { "value": "150ms", "type": "duration" },
      "standard": { "value": "300ms", "type": "duration" }
    }
  }
}`,
  },
  universalConfig: `{
  "meta": {
    "brand": "[BRAND_NAME]",
    "version": "1.0.0",
    "generated": "2026-03-11T00:00:00Z",
    "agency": "JKR Global"
  },
  "identity": {
    "visual_descriptors": ["[STYLE_1]", "[STYLE_2]", "[STYLE_3]"],
    "colour_mood": "[COLOUR_MOOD]",
    "typography_character": "[TYPE_CHARACTER]"
  },
  "imageGenPrompts": {
    "midjourney": "...",
    "dalle": "...",
    "firefly": "..."
  },
  "llmSystemPrompts": {
    "full": "...",
    "concise": "...",
    "imageContext": "..."
  },
  "designTokens": {
    "colours": {},
    "typography": {},
    "motion": {}
  }
}`,
};

interface CopiedState {
  [key: string]: boolean;
}

export default function OutputsPage() {
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [copied, setCopied] = useState<CopiedState>({});

  async function generateConfig() {
    setGenerating(true);
    // In production: POST to /api/brands/[brandId]/generate
    setTimeout(() => {
      setGenerating(false);
      setGenerated(true);
    }, 3000);
  }

  async function copyToClipboard(key: string, text: string) {
    await navigator.clipboard.writeText(text);
    setCopied((prev) => ({ ...prev, [key]: true }));
    setTimeout(() => setCopied((prev) => ({ ...prev, [key]: false })), 2000);
  }

  const platforms = [
    {
      id: "midjourney",
      name: "Midjourney",
      badge: "Image Gen",
      description: "Style reference prompt with parameters for Midjourney v6",
      content: PLACEHOLDER_OUTPUTS.midjourney,
    },
    {
      id: "dalle",
      name: "DALL-E 3",
      badge: "Image Gen",
      description: "Detailed system prompt for OpenAI DALL-E 3",
      content: PLACEHOLDER_OUTPUTS.dalle,
    },
    {
      id: "firefly",
      name: "Adobe Firefly",
      badge: "Image Gen",
      description: "Style descriptor for Adobe Firefly generative AI",
      content: PLACEHOLDER_OUTPUTS.firefly,
    },
    {
      id: "claude",
      name: "Claude / ChatGPT",
      badge: "LLM Prompt",
      description: "Full brand system prompt for Claude, ChatGPT, and other LLMs",
      content: PLACEHOLDER_OUTPUTS.claude,
    },
  ];

  return (
    <div className="p-8 max-w-5xl">
      <div className="mb-8 flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">AI Outputs</h1>
          <p className="mt-1 text-sm text-[var(--muted-foreground)]">
            Generate machine-readable brand configs and platform-specific prompts from your brand system.
          </p>
        </div>
        <Button onClick={generateConfig} disabled={generating}>
          {generating ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Zap className="mr-2 h-4 w-4" />
              {generated ? "Regenerate" : "Generate Brand Config"}
            </>
          )}
        </Button>
      </div>

      {!generated && !generating && (
        <Card className="mb-6 border-dashed">
          <CardContent className="flex flex-col items-center justify-center py-16 text-center">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-[var(--muted)]">
              <Zap className="h-6 w-6 text-[var(--muted-foreground)]" />
            </div>
            <h3 className="mt-4 text-sm font-semibold">Ready to generate</h3>
            <p className="mt-1.5 max-w-sm text-sm text-[var(--muted-foreground)]">
              Complete the brand system modules then click Generate to create AI-ready configs for all platforms.
            </p>
            <div className="mt-4 flex flex-wrap justify-center gap-2">
              {["Midjourney", "DALL-E 3", "Adobe Firefly", "Claude", "ChatGPT", "Canva AI", "Design Tokens"].map(
                (p) => (
                  <Badge key={p} variant="secondary">{p}</Badge>
                )
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {generating && (
        <Card className="mb-6">
          <CardContent className="py-10">
            <div className="flex flex-col items-center gap-4">
              <Loader2 className="h-8 w-8 animate-spin text-[var(--primary)]" />
              <div className="text-center">
                <p className="text-sm font-medium">Brand Intelligence Engine running</p>
                <p className="text-xs text-[var(--muted-foreground)] mt-1">
                  Claude is synthesising your brand system into AI-ready outputs...
                </p>
              </div>
              <div className="flex flex-col gap-2 w-full max-w-xs">
                {[
                  "Analysing visual identity...",
                  "Building colour descriptors...",
                  "Generating image prompts...",
                  "Crafting LLM system prompts...",
                  "Exporting design tokens...",
                ].map((step, i) => (
                  <div key={step} className="flex items-center gap-2 text-xs">
                    <div className="h-1.5 w-1.5 rounded-full bg-[var(--primary)] animate-pulse" style={{ animationDelay: `${i * 0.3}s` }} />
                    <span className="text-[var(--muted-foreground)]">{step}</span>
                  </div>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {generated && (
        <Tabs defaultValue="image-gen">
          <TabsList className="mb-6">
            <TabsTrigger value="image-gen">Image Generation</TabsTrigger>
            <TabsTrigger value="llm">LLM System Prompts</TabsTrigger>
            <TabsTrigger value="tokens">Design Tokens</TabsTrigger>
            <TabsTrigger value="universal">Universal Config</TabsTrigger>
          </TabsList>

          <TabsContent value="image-gen" className="space-y-4">
            {platforms.slice(0, 3).map((platform) => (
              <Card key={platform.id}>
                <CardHeader className="pb-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <CardTitle className="text-base">{platform.name}</CardTitle>
                      <Badge variant="secondary">{platform.badge}</Badge>
                    </div>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => copyToClipboard(platform.id, platform.content)}
                    >
                      {copied[platform.id] ? (
                        <><Check className="mr-1.5 h-3.5 w-3.5 text-emerald-500" />Copied</>
                      ) : (
                        <><Copy className="mr-1.5 h-3.5 w-3.5" />Copy</>
                      )}
                    </Button>
                  </div>
                  <CardDescription>{platform.description}</CardDescription>
                </CardHeader>
                <CardContent>
                  <pre className="rounded-lg bg-[var(--muted)] p-4 text-xs font-mono whitespace-pre-wrap overflow-auto max-h-48 text-[var(--foreground)]">
                    {platform.content}
                  </pre>
                </CardContent>
              </Card>
            ))}
          </TabsContent>

          <TabsContent value="llm" className="space-y-4">
            <Card>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <CardTitle className="text-base">Claude / ChatGPT System Prompt</CardTitle>
                    <Badge variant="secondary">LLM Prompt</Badge>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard("claude", PLACEHOLDER_OUTPUTS.claude)}>
                      {copied["claude"] ? <><Check className="mr-1.5 h-3.5 w-3.5 text-emerald-500" />Copied</> : <><Copy className="mr-1.5 h-3.5 w-3.5" />Copy</>}
                    </Button>
                    <Button variant="outline" size="sm">
                      <Download className="mr-1.5 h-3.5 w-3.5" />Export
                    </Button>
                  </div>
                </div>
                <CardDescription>Full system prompt covering brand voice, visual guidelines, and usage rules</CardDescription>
              </CardHeader>
              <CardContent>
                <pre className="rounded-lg bg-[var(--muted)] p-4 text-xs font-mono whitespace-pre-wrap overflow-auto max-h-96 text-[var(--foreground)]">
                  {PLACEHOLDER_OUTPUTS.claude}
                </pre>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="tokens" className="space-y-4">
            <Card>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-base">CSS Custom Properties</CardTitle>
                  <Button variant="outline" size="sm" onClick={() => copyToClipboard("css", PLACEHOLDER_OUTPUTS.designTokens.css)}>
                    {copied["css"] ? <><Check className="mr-1.5 h-3.5 w-3.5 text-emerald-500" />Copied</> : <><Copy className="mr-1.5 h-3.5 w-3.5" />Copy</>}
                  </Button>
                </div>
                <CardDescription>Brand design tokens as CSS variables — drop into any web project</CardDescription>
              </CardHeader>
              <CardContent>
                <pre className="rounded-lg bg-[var(--muted)] p-4 text-xs font-mono whitespace-pre-wrap overflow-auto max-h-64">
                  {PLACEHOLDER_OUTPUTS.designTokens.css}
                </pre>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-base">JSON Tokens</CardTitle>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard("json", PLACEHOLDER_OUTPUTS.designTokens.json)}>
                      {copied["json"] ? <><Check className="mr-1.5 h-3.5 w-3.5 text-emerald-500" />Copied</> : <><Copy className="mr-1.5 h-3.5 w-3.5" />Copy</>}
                    </Button>
                    <Button variant="outline" size="sm"><Download className="mr-1.5 h-3.5 w-3.5" />tokens.json</Button>
                  </div>
                </div>
                <CardDescription>W3C Design Token format — compatible with Style Dictionary, Figma Tokens, and other tools</CardDescription>
              </CardHeader>
              <CardContent>
                <pre className="rounded-lg bg-[var(--muted)] p-4 text-xs font-mono whitespace-pre-wrap overflow-auto max-h-64">
                  {PLACEHOLDER_OUTPUTS.designTokens.json}
                </pre>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="universal">
            <Card>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="text-base">Universal Brand Config</CardTitle>
                    <CardDescription className="mt-1">Complete machine-readable brand intelligence package — use via API or export as JSON</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={() => copyToClipboard("universal", PLACEHOLDER_OUTPUTS.universalConfig)}>
                      {copied["universal"] ? <><Check className="mr-1.5 h-3.5 w-3.5 text-emerald-500" />Copied</> : <><Copy className="mr-1.5 h-3.5 w-3.5" />Copy</>}
                    </Button>
                    <Button variant="outline" size="sm"><Download className="mr-1.5 h-3.5 w-3.5" />brand-config.json</Button>
                    <Button variant="secondary" size="sm"><RefreshCw className="mr-1.5 h-3.5 w-3.5" />Regenerate</Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <pre className="rounded-lg bg-[var(--muted)] p-4 text-xs font-mono whitespace-pre-wrap overflow-auto max-h-96">
                  {PLACEHOLDER_OUTPUTS.universalConfig}
                </pre>
              </CardContent>
            </Card>

            {/* API Access */}
            <Card className="mt-4">
              <CardHeader>
                <CardTitle className="text-base">API Access</CardTitle>
                <CardDescription>Programmatically access this brand config from any platform</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="rounded-lg bg-[var(--muted)] p-4">
                  <p className="text-xs text-[var(--muted-foreground)] mb-2">GET</p>
                  <code className="text-xs font-mono">
                    https://api.brandintelligence.jkr/v1/brands/[BRAND_ID]/config
                  </code>
                </div>
                <p className="mt-3 text-xs text-[var(--muted-foreground)]">
                  Returns the full brand config JSON. Authenticate with your API key. Plug directly into any AI creative platform or custom integration.
                </p>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      )}
    </div>
  );
}
